# Example Task Queue Configuration File
# This file demonstrates how to configure the rust-task-queue crate using TOML

[redis]
url = "redis://127.0.0.1:6379"
pool_size = 10
connection_timeout = 30  # seconds
command_timeout = 10     # seconds

[workers]
initial_count = 4
max_concurrent_tasks = 50
heartbeat_interval = 30  # seconds
shutdown_grace_period = 10  # seconds

[autoscaler]
enabled = true
min_workers = 2
max_workers = 20
scale_up_threshold = 5.0
scale_down_threshold = 2.0
scale_up_cooldown = 60   # seconds
scale_down_cooldown = 300  # seconds

[auto_register]
enabled = true

[scheduler]
enabled = true
tick_interval = 10  # seconds
max_tasks_per_tick = 100

# Actix Web integration settings (only used when actix-integration feature is enabled)
[actix]
auto_configure_routes = true
route_prefix = "/rust-task-queue"
enable_metrics = true
enable_health_check = true 