services:
  app:
    build: .
    command: cargo run --color=always --bin web-server
    ports:
      - "8000:8000"
    working_dir: /app/examples/axum-integration
    volumes:
      - ../../:/app
    depends_on:
      - redis

  worker:
    build: .
    command: cargo run --color=always --bin task-worker
    working_dir: /app/examples/axum-integration
    volumes:
      - ../../:/app
    environment:
      - LOG_FORMAT=json
      - LOG_LEVEL=info
    depends_on:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    restart: unless-stopped

volumes:
  redis:

